//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.14 at 06:52:53 PM BRT 
//


package com.rmemoria.datastream.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for graphSchema complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="graphSchema">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="objectGraph" type="{}objectGraph" minOccurs="0"/>
 *         &lt;element name="objectCollection" type="{}objectCollection" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name="graphSchema")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "graphSchema", propOrder = {
    "objectGraph",
    "objectCollection"
})
public class GraphSchema {

    protected ObjectGraph objectGraph;
    protected ObjectCollection objectCollection;

    /**
     * Gets the value of the objectGraph property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectGraph }
     *     
     */
    public ObjectGraph getObjectGraph() {
        return objectGraph;
    }

    /**
     * Sets the value of the objectGraph property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectGraph }
     *     
     */
    public void setObjectGraph(ObjectGraph value) {
        this.objectGraph = value;
    }

    /**
     * Gets the value of the objectCollection property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectCollection }
     *     
     */
    public ObjectCollection getObjectCollection() {
        return objectCollection;
    }

    /**
     * Sets the value of the objectCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectCollection }
     *     
     */
    public void setObjectCollection(ObjectCollection value) {
        this.objectCollection = value;
    }

}
